name: Symfony Console

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  symfony-console-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Show PHP and Symfony info
        run: |
          php -v
          php bin/console --version || echo "Symfony console not found"
